### ISSUE TITLE
Line orientation 

### ISSUE THREAD

**Issue by sunithvs** [Trebuchet-ltd/xr-lab-home-page#6]
![image](https://user-images.githubusercontent.com/63339782/178142058-691b68bf-1de1-496b-a781-4ae4b08bba42.png)
These line must look like these 
![image](https://user-images.githubusercontent.com/63339782/178142089-8292934d-46e1-4daf-b651-134e9d60aa3c.png)

**Comment by Alimiyan** [comment]
Fixed.
